module.exports = [
  'aignment',
  'alpha',
  'bandwidth',
  'big data',
  'boots on the ground',
  'brand',
  'chage agent',
  'content marketing',
  'early adopter',
  'ecosystem',
  'enterprise',
  'footprint',
  'game-changer',
  'grit',
  'ideation',
  'industry',
  'innovation',
  'low-hanging fruit',
  'mindshare',
  'minimum viable product',
  'narrative',
  'onboarding',
  'optics',
  'paradigm',
  'passion',
  'platform',
  'playing field',
  'solution',
  'thought leader',
  'traction',
  'transformation',
  'value-add',
  'vector',
  'visibility',
  'wheelhouse',
];