module.exports = [
  'benchmark',
  'circle back',
  'close the loop',
  'cross-polinate',
  'curate',
  'dialog',
  'disrupt',
  'drill down',
  'drive',
  'empower',
  'future-proof',
  'gamify',
  'ideate',
  'leverage',
  'move the needle',
  'open the kimono',
  'pivot',
  'push the envelope',
  'reach out',
  'recontextualize',
  're-imagine',
  'roll out',
  'silo',
  'synthesize',
  'taper',
  'transform',
];
